package com.elleined.socialmediaapi.repository.notification.reaction;

import com.elleined.socialmediaapi.model.notification.reaction.CommentReactionNotification;

public interface CommentReactionNotificationRepository extends ReactionNotificationRepository<CommentReactionNotification> {
}